<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
    <AssemblyName>TaskWall</AssemblyName>
    <RootNamespace>TaskWall</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.10.0</Version>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Product>TaskWall</Product>
    <!-- smaller memory footprint for a tray-style app -->
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <TieredPGO>false</TieredPGO>
    <SatelliteResourceLanguages>pl</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.GC.ConserveMemory" Value="7" />
  </ItemGroup>

</Project>

